# Generated by Django 5.2.4 on 2025-08-13 23:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_envases_por_kg', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio de envases por kilogramo de producto', max_digits=8, verbose_name='Costo Envases por KG')),
                ('costo_etiquetas_por_unidad', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio de etiquetas por unidad de producto', max_digits=8, verbose_name='Costo Etiquetas por Unidad')),
                ('costo_envio_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio de envío por producto', max_digits=8, verbose_name='Costo Envío Promedio')),
                ('tiempo_fraccionamiento_por_kg', models.DecimalField(decimal_places=2, default=0, help_text='Minutos necesarios para fraccionar 1 kg de producto', max_digits=5, verbose_name='Tiempo Fraccionamiento (min/kg)')),
                ('valor_hora_trabajo', models.DecimalField(decimal_places=2, default=0, help_text='Valor por hora de trabajo del emprendedor', max_digits=8, verbose_name='Valor Hora de Trabajo')),
                ('incluir_costos_indirectos', models.BooleanField(default=False, help_text='Si está marcado, se incluyen costos indirectos en el cálculo', verbose_name='Incluir Costos Indirectos')),
                ('redondear_precios', models.BooleanField(default=True, help_text='Redondear precios finales al peso más cercano', verbose_name='Redondear Precios')),
                ('actualizar_automaticamente', models.BooleanField(default=True, help_text='Actualizar precios cuando cambian los costos de materias primas', verbose_name='Actualizar Precios Automáticamente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Costos',
                'verbose_name_plural': 'Configuración de Costos',
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidades'), ('m', 'Metros'), ('cm', 'Centímetros')], max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'ordering': ['nombre'],
                'permissions': [('can_manage_materias_primas', 'Puede gestionar materias primas'), ('can_view_stock_reports', 'Puede ver reportes de stock')],
            },
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateField()),
                ('fecha_consumo', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='gestion.materiaprima')),
            ],
            options={
                'verbose_name': 'Lote de Materia Prima',
                'verbose_name_plural': 'Lotes de Materias Primas',
                'ordering': ['fecha_entrada', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('cantidad_mayoreo', models.DecimalField(decimal_places=2, help_text='Cantidad comprada (usa la unidad de la materia prima)', max_digits=10)),
                ('precio_mayoreo', models.DecimalField(decimal_places=2, help_text='Precio total de la compra', max_digits=10)),
                ('precio_unitario_mayoreo', models.DecimalField(decimal_places=2, editable=False, help_text='Precio unitario (calculado automáticamente)', max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='gestion.materiaprima')),
            ],
            options={
                'verbose_name': 'Compra al Mayoreo',
                'verbose_name_plural': 'Compras al Mayoreo',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste de Inventario'), ('produccion', 'Uso en Producción'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.materiaprima')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Materia Prima',
                'verbose_name_plural': 'Movimientos de Materias Primas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('operador', 'Operador'), ('vendedor', 'Vendedor')], default='operador', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(default='otros', help_text='Categoría del producto. Puede usar una existente o crear una nueva.', max_length=50)),
                ('atributos_dieteticos', models.CharField(blank=True, help_text='Ej: orgánico,vegano,sin_tacc (separados por comas)', max_length=200)),
                ('marca', models.CharField(blank=True, help_text='Marca del producto', max_length=100)),
                ('origen', models.CharField(blank=True, help_text='Origen del producto', max_length=100)),
                ('stock_minimo', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiene_receta', models.BooleanField(default=False, help_text='Marcar si el producto se produce a partir de una receta', verbose_name='¿Usa receta?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_producto', models.CharField(choices=[('reventa', 'Reventa Directa'), ('fraccionamiento', 'Fraccionamiento'), ('receta', 'Con Receta')], default='reventa', help_text='Define cómo se calcula el costo del producto', max_length=20, verbose_name='Tipo de Producto')),
                ('costo_base', models.DecimalField(blank=True, decimal_places=2, help_text='Costo calculado automáticamente según el tipo de producto', max_digits=10, null=True, verbose_name='Costo Base Unitario')),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de ganancia sobre el costo base', max_digits=5, verbose_name='Margen de Ganancia (%)')),
                ('precio_venta_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Precio calculado automáticamente: costo_base + margen', max_digits=10, null=True, verbose_name='Precio de Venta Calculado')),
                ('actualizar_precio_automatico', models.BooleanField(default=True, help_text='Si está marcado, el precio se actualiza cuando cambian los costos', verbose_name='Actualizar Precio Automáticamente')),
                ('unidad_compra', models.CharField(default='kg', help_text='Unidad en que se compra el producto origen', max_length=10, verbose_name='Unidad de Compra')),
                ('unidad_venta', models.CharField(default='kg', help_text='Unidad en que se vende este producto', max_length=10, verbose_name='Unidad de Venta')),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=1.0, help_text='Cuántas unidades de venta salen de 1 unidad de compra', max_digits=10, verbose_name='Factor de Conversión')),
                ('cantidad_origen', models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad que se compra del producto origen', max_digits=10, null=True, verbose_name='Cantidad del Producto Origen')),
                ('cantidad_fraccion', models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad que contiene cada fracción', max_digits=10, null=True, verbose_name='Cantidad por Fracción')),
                ('materia_prima_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_asociados', to='gestion.materiaprima')),
                ('producto_origen', models.ForeignKey(blank=True, help_text='Producto del cual se fracciona (para tipo fraccionamiento)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_fraccionados', to='gestion.producto', verbose_name='Producto de Origen')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('costo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.CharField(help_text='Razón del cambio de costo/precio', max_length=200)),
                ('precio_materia_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_materia_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('materia_prima_afectada', models.ForeignKey(blank=True, help_text='Materia prima que causó el cambio (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.materiaprima')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_costos', to='gestion.producto')),
            ],
            options={
                'verbose_name': 'Histórico de Costo',
                'verbose_name_plural': 'Histórico de Costos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, help_text='Cantidad de materia prima necesaria por unidad de producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='gestion.materiaprima')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='gestion.producto')),
            ],
            options={
                'verbose_name': 'Receta de Producto',
                'verbose_name_plural': 'Recetas de Productos',
                'unique_together': {('producto', 'materia_prima')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='receta',
            field=models.ForeignKey(blank=True, help_text='Selecciona la receta principal si corresponde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_con_receta', to='gestion.productomateriaprima', verbose_name='Receta principal'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Receta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, verbose_name='Receta Activa')),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('productos', models.ManyToManyField(blank=True, related_name='recetas_producto', to='gestion.producto', verbose_name='Productos que usan esta receta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad Necesaria')),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidades'), ('m', 'Metros'), ('cm', 'Centímetros')], default='kg', max_length=20, verbose_name='Unidad de Medida')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas especiales')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materiaprima')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.receta')),
            ],
            options={
                'verbose_name': 'Materia Prima en Receta',
                'verbose_name_plural': 'Materias Primas en Recetas',
                'unique_together': {('receta', 'materia_prima')},
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='materias_primas',
            field=models.ManyToManyField(related_name='recetas_materia', through='gestion.RecetaMateriaPrima', to='gestion.materiaprima', verbose_name='Materias Primas necesarias'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.venta')),
            ],
        ),
    ]
