# Generated by Django 5.2.4 on 2025-08-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='receta',
            field=models.ForeignKey(blank=True, help_text='Selecciona la receta principal si corresponde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_con_receta', to='gestion.receta', verbose_name='Receta principal'),
        ),
    ]
