# Generated by Django 5.2.4 on 2025-10-20 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_producto_receta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPreciosMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Anterior por Unidad')),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Nuevo por Unidad')),
                ('proveedor_anterior', models.CharField(blank=True, max_length=200)),
                ('proveedor_nuevo', models.CharField(blank=True, max_length=200)),
                ('motivo', models.TextField(blank=True, help_text='Razón del cambio de precio (ej: nueva compra, inflación, cambio de proveedor)', verbose_name='Motivo del cambio')),
                ('productos_afectados_count', models.PositiveIntegerField(default=0, help_text='Cantidad de productos que usan esta materia prima', verbose_name='Productos Afectados')),
            ],
            options={
                'verbose_name': 'Historial de Precios - Materia Prima',
                'verbose_name_plural': 'Historial de Precios - Materias Primas',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='eliminada',
            field=models.BooleanField(default=False, help_text='Marca la venta como eliminada sin borrar el registro', verbose_name='Venta Eliminada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='razon_eliminacion',
            field=models.TextField(blank=True, help_text='Motivo por el cual se eliminó la venta', verbose_name='Razón de Eliminación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_eliminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Eliminó'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha', 'eliminada'], name='venta_fecha_eliminada_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['eliminada'], name='venta_eliminada_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario'], name='venta_usuario_idx'),
        ),
        migrations.AddField(
            model_name='historialpreciosmateriaprima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='gestion.materiaprima'),
        ),
        migrations.AddField(
            model_name='historialpreciosmateriaprima',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio'),
        ),
        migrations.AddIndex(
            model_name='historialpreciosmateriaprima',
            index=models.Index(fields=['materia_prima', 'fecha_cambio'], name='mp_historial_idx'),
        ),
        migrations.AddIndex(
            model_name='historialpreciosmateriaprima',
            index=models.Index(fields=['fecha_cambio'], name='fecha_cambio_idx'),
        ),
    ]
