# Generated by Django 5.2.4 on 2025-11-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_add_soft_deletes_and_price_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_agotado', 'Stock Agotado'), ('stock_critico', 'Stock Crítico'), ('vencimiento', 'Próximo a Vencer'), ('margen_negativo', 'Margen Negativo'), ('margen_bajo', 'Margen Bajo'), ('stock_muerto', 'Stock Muerto'), ('oportunidad_venta', 'Oportunidad de Venta')], max_length=30, verbose_name='Tipo de Alerta')),
                ('nivel', models.CharField(choices=[('danger', 'Peligro'), ('warning', 'Advertencia'), ('success', 'Oportunidad'), ('info', 'Información')], default='info', max_length=10, verbose_name='Nivel de Severidad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje Detallado')),
                ('valor_impacto', models.DecimalField(blank=True, decimal_places=2, help_text='Pérdida potencial o ganancia estimada en pesos', max_digits=12, null=True, verbose_name='Valor de Impacto ($)')),
                ('accion_sugerida', models.TextField(blank=True, help_text='Recomendación específica para resolver la alerta', verbose_name='Acción Sugerida')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha límite de relevancia de la alerta', null=True, verbose_name='Fecha de Expiración')),
                ('leida', models.BooleanField(default=False, help_text='Indica si el usuario ha visto la alerta', verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('archivada', models.BooleanField(default=False, help_text='Indica si la alerta fue archivada manualmente', verbose_name='Archivada')),
                ('fecha_archivo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Archivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='gestion.producto', verbose_name='Producto Relacionado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destinatario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
                'permissions': [('can_view_all_alertas', 'Puede ver todas las alertas'), ('can_manage_alertas', 'Puede gestionar alertas')],
                'indexes': [models.Index(fields=['usuario', 'leida', 'archivada'], name='alerta_usuario_estado_idx'), models.Index(fields=['tipo', 'nivel'], name='alerta_tipo_nivel_idx'), models.Index(fields=['producto', 'tipo'], name='alerta_producto_tipo_idx'), models.Index(fields=['fecha_creacion'], name='alerta_fecha_idx')],
            },
        ),
    ]
