# Generated by Django 5.2.4 on 2025-11-05 04:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncostos',
            name='cobertura_objetivo_dias',
            field=models.IntegerField(default=30, help_text='Días de cobertura ideal de stock (ej: 30 días)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cobertura Objetivo (días)'),
        ),
        migrations.AddField(
            model_name='configuracioncostos',
            name='margen_objetivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Margen de rentabilidad objetivo para el negocio (ej: 35%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Margen Objetivo (%)'),
        ),
        migrations.AddField(
            model_name='configuracioncostos',
            name='rotacion_objetivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Veces que el inventario debería rotar por mes (ej: 4x)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rotación Objetivo (veces/mes)'),
        ),
    ]
