# Generated by Django 5.2.4 on 2025-11-06 01:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_configuracioncostos_cobertura_objetivo_dias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total del Pedido'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo legacy - usar CompraDetalle para nuevas compras', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='materia_prima',
            field=models.ForeignKey(blank=True, help_text='Campo legacy - usar CompraDetalle para nuevas compras', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='gestion.materiaprima'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo legacy - usar CompraDetalle para nuevas compras', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_unitario_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Campo legacy - usar CompraDetalle para nuevas compras', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.CharField(max_length=100, verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad comprada (usa la unidad de la materia prima)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad de medida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Calculado automáticamente: cantidad × precio_unitario', max_digits=12, verbose_name='Subtotal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.compra', verbose_name='Compra')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materiaprima', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'ordering': ['id'],
            },
        ),
    ]
