# Generated by Django 5.2.4 on 2025-11-07 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_compra_observaciones_compra_total_compra_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Anterior')),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Nuevo')),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='Positivo = incremento, Negativo = reducción', max_digits=10, verbose_name='Diferencia')),
                ('tipo', models.CharField(choices=[('INVENTARIO_FISICO', 'Inventario Físico'), ('MERMA', 'Merma / Pérdida'), ('CORRECCION', 'Corrección de Error'), ('VENCIDO', 'Producto/MP Vencido'), ('REGALO', 'Regalo / Muestra'), ('DANIO', 'Daño / Derrame'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Ajuste')),
                ('razon', models.TextField(help_text='Descripción detallada del motivo del ajuste', verbose_name='Razón del Ajuste')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='gestion.materiaprima', verbose_name='Materia Prima')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='gestion.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', 'fecha'], name='ajuste_producto_idx'), models.Index(fields=['materia_prima', 'fecha'], name='ajuste_mp_idx'), models.Index(fields=['tipo', 'fecha'], name='ajuste_tipo_idx'), models.Index(fields=['fecha'], name='ajuste_fecha_idx')],
            },
        ),
    ]
